// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDdkcz7wAHV8LURCEETdaqzfgWeOCYfDc',
    appId: '1:1083082948224:android:300652e689c82a09d17065',
    messagingSenderId: '1083082948224',
    projectId: 'meddict-191cc',
    databaseURL: 'https://meddict-191cc-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'meddict-191cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuaCfXVAY7IiTLZUeGGu35UubshB9nDy0',
    appId: '1:1083082948224:ios:5903d11e1bed6775d17065',
    messagingSenderId: '1083082948224',
    projectId: 'meddict-191cc',
    databaseURL: 'https://meddict-191cc-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'meddict-191cc.firebasestorage.app',
    androidClientId: '1083082948224-hv1lf6l3cpqjhueemmmfhnd0lpsp2mtu.apps.googleusercontent.com',
    iosClientId: '1083082948224-btimpk4gmbi83tjf2jojva5166b7l8vc.apps.googleusercontent.com',
    iosBundleId: 'pleiner.jakob.meddict',
  );

}